### ISSUE TITLE
When do we use px as opposed to rem? 

### ISSUE THREAD

**Issue by richlloydmiles** [Nona-Creative/coding-standards#13]
- Coding standards talk about rem in typography - https://github.com/Nona-Creative/coding-standards/tree/master/scss#units while in other places the use of px is good - https://github.com/Nona-Creative/coding-standards/tree/master/scss#css. I can see how the use of border width can be fixed to a px value, but would this not also apply to something like max-width or height on a banner?

- Also taking into account rem calculations can only take one argument, so how would something like this be achieved - https://github.com/Nona-Creative/coding-standards/tree/master/scss#shorthand-selectors.

@leogopal @Ricus-Rossouw @Sntax @royscheeren @mattkombo  any thoughts?

**Comment by royscheeren** [comment]
On your second item using a function instead of a mixin would solve that issue. Given that ie8 is the last browser that doesnt support rem I think we can safely drop px fallback support.

**Comment by Pushplaybang** [comment]
Border is of particular interest as using `box-sizing: border-box` means that it no longer affects the dimensions. 

For max-widths, or heights etc, these should certainly be REM's, which will allow for truly responsive, and elastic layouts to be achieved far more easily.

I absolutely agree about the shorthand properties, knife.scss could use some love, if you're feeling up to adding a function for shorthand props, or @royscheeren - removing ie8 fallback  head on over to the knife repo, or just do it in your project, but would be nice to have the contribution.  I've just never gotten there.  (I do often find it easy to manually put these values in though)

https://github.com/Pushplaybang/knife

**Comment by Pushplaybang** [comment]
@richlloydmiles @royscheeren does this warrant further discussion?

regarding your comment about using a function, knife includes a calculateRem function which we use all the time for various values.

**Comment by richlloydmiles** [comment]
Ye I' m happy with the response thanks @Pushplaybang and @royscheeren for the feedback

**Comment by royscheeren** [comment]
Don't think we need much more discussion on this. I'm with you on the REMS on borders. Which is one of the few things where I don't really use REM. Borders, shadows etc don't really need adaptation when zooming in and out on a site or changing viewport sizes.
