### ISSUE TITLE
SCSS Spacing

### ISSUE THREAD

**Issue by richlloydmiles** [Nona-Creative/coding-standards#15]
I am unclear as to which of the following examples are correct in scss nested formatting:

> https://github.com/Nona-Creative/coding-standards/tree/master/scss#formatting
> 
> @ Put blank lines between rule declarations
> 

**1:**

Empty declarations (div) need a new line but no new lines when closing nested declarations.
```
div {

  a {
// some scss
  }
}
```

**2:**

Empty declaration (div) new lines are redundant and don't need a new line.
```
div {
  a {
// some scss
  }
}
```

**3:**

Empty declarations (div) need a new line as well as closing nested declarations.
```
div {

  a {
// some scss
  }

}
```

**Comment by royscheeren** [comment]
I believe door nr 1 is the way to go.

**Comment by ShaunEgan** [comment]
I don't think there is a standard when it come's to blank lines other than _not more than one_. Use them to try group related statements or operations.

**Comment by solnona** [comment]
There is a standard, we decided to use option n 2

**Comment by Sntax** [comment]
I don't see the benefit to nesting at all in this case. 

Why not: 

```
div a {
  // some scss
}
```

**Comment by SkippyZA** [comment]
tbh, 1 or 3 is better than 2.
2 is extremely cramped.

**Comment by solnona** [comment]
If we have more rules, they need space between them, like this:
```
div {
  a {
    // some scss
  }

  p {
    // some more scss
  }
}
```

**Comment by solnona** [comment]
@SkippyZA we've been finding this a lot easier to read when there is actual code written
@Sntax This is only as an example

**Comment by Pushplaybang** [comment]
@sol is correct in terms of the standard.  As with JS you don't have blank line padding inside a block, but you would have between block declarations.

no. 2 it is.
