### ISSUE TITLE
JS - single line guard clauses and single line conditionals

### ISSUE THREAD

**Issue by Pushplaybang** [Nona-Creative/coding-standards#17]
I'd like to propose we start using the quite terse, and very readable form for single line conditionals, in particular, guard clauses:

```js
// current
if (!this || !this.roles) {
  return null;
}

// proposal 1
if (!this || !this.roles) return null;

// proposal 2
if (!this || !this.roles) 
  return null;
```

While there is no functional difference, it always feels unnecessary to me.  

Love it, hate it, or rate it.  Let's go.

@ShaunEgan @Sntax @JamesGarethSmith @Ricus-Rossouw @royscheeren @dynten

**Comment by ShaunEgan** [comment]
I used to be against this, but used it all the time in `scala` and wound up using it quite often. I am totally up for `proposal 1`.

Let me just add `(!this || !this.roles)` looks gross A suggestion (not a rule) for this going forward is to have guard predicates like this in a named function for better readability. i.e..

```js
// guard predicate
const rolesNotSet = object => !object || !object.roles;

// ...

if (rolesNotSet) return null;
```

**Comment by Sntax** [comment]
I'm 100% on board with Proposal 1 as it's something we have already begun to do on OrderIn Web.

**Comment by JamesGarethSmith** [comment]
I don't have a preference between the way we do it now and proposal 1. This seems more like a personal preference issue. 

I am however definitely against proposal 2 (too easy to introduce errors).

And most importantly of all, what @ShaunEgan said. Naming the conditional is far more important than how you structure the conditional. Super-important for indicating your intent.

**Comment by Pushplaybang** [comment]
awesome, and agreed on all counts, please excuse my shitty example :)

**Comment by ShaunEgan** [comment]
Cool, are you going to update the style guide and close this with that PR?

**Comment by Pushplaybang** [comment]
yeah, I'm on it.

**Comment by ShaunEgan** [comment]
Close?
