### ISSUE TITLE
Create General purpose non language specific Coding Best Practices

### ISSUE THREAD

**Issue by Pushplaybang** [Nona-Creative/coding-standards#5]
elements such as variable and argument naming, avoiding side effects in functions etc

**Comment by Pushplaybang** [comment]
Suggestions Welcome, here's a few random ones:

* Commenting (DocBLocks? - should be agreed as to how)
* Naming conventions (being explicit etc, )
* Avoiding deep nesting
* encapsulation and abstraction
* keeping code DRY
* Separation of concerns

**Comment by ShaunEgan** [comment]
I feel that this is just setting up a list of things a good programmer should do. We should not be spending time trying to codify this - rather be making sure that the people we bring into the business are already capable programmers and that PRs highlight the occasional slip-up. 

Alternatively - the list would be fairly short:

1. Good Object Orientation 
2. SOLID 
3. Style decisions come from the agreed upon stand for the language / framework you are using.

**Comment by SkippyZA** [comment]
Read the book "Clean Code"

**Comment by SkippyZA** [comment]
Actually, can we get a physical copy of Clean Code for the office?

**Comment by JamesGarethSmith** [comment]
@SkippyZA Beat me to it. This is exactly the type of book we should have and encourage people to read.

I agree with @ShaunEgan that we don't necessarily have to codify these kind of standards (this is just being a professional developer). 

But on the other hand we can't always expect people to arrive at the company fully formed. There is some onus on us to bring everyone forward together; by setting a good example, not accepting anything less than a professional standard and being available to help.

**Comment by Pushplaybang** [comment]
agree about the book - please speak to @NatashaSunjich  regarding the book.  

I do think there's some value in developing a unified set of guidelines, especially for younger developers, and the internet is ablaze with varying opinion on many "best practice" concepts.  

The important part of it is about finding an agreement we can all hold each other to.

**Comment by SkippyZA** [comment]
yay for the book! @JamesGarethSmith, you want to organise with Tash?

**Comment by JamesGarethSmith** [comment]
Sure thing, I'll chat to Tash today.

**Comment by Ricus-Rossouw** [comment]
What is this 'book' thing you guys are speaking about :D  I heard it was
compiled using one of those ancient pen devices..

On Fri, Sep 16, 2016 at 8:12 AM, James Gareth Smith <
       @|SENDERNAME@ @|SENDERSURNAME@
Code | nonacreative.com
O. 021 200 5958 | F. 086 240 5730

**Comment by ShaunEgan** [comment]
I still feel that best practices are not Nona specific and that we should be able to point to external references for that. 

If there is a desperate need for this kind of thing, then maybe it should be a list of resources to reference, such as:

### General
* Clean Code

### Java
* Effective Java

### Scala 
* Programming in Scala

Etc...

**Comment by JamesGarethSmith** [comment]
I chatted to Tash and she going/already has ordered *Clean Code*.

I think we should, at least initially, go for books with a more general focus. Some ideas:

- *The Pragmatic Programmer*
- *Refactoring: Improving the Design of Existing Code*
- *Code Complete*
- *Working Effectively with Legacy Code*

**Comment by leogopal** [comment]
are we getting the digital or Physical books?

**Comment by JamesGarethSmith** [comment]
Physical.

**Comment by Pushplaybang** [comment]
#16 relates to my original thought around this, as a sort of general quick reference for code style / standard best practices, but I think this issue has evolved into so much more as the discussion started by @SkippyZA  sparked.  @JamesGarethSmith has pushed on this as well so we're up for building a little nona library.

We've also started some direct discussion around mentorship and put enough in motion that I feel this issue is resolved.  

Go team.
