### ISSUE TITLE
Ruby Standards

### ISSUE THREAD

**Issue by Pushplaybang** [Nona-Creative/coding-standards#6]
# Scope
We should centralize our agreed standards for ruby, and rails code as a part of this central standards reference.  After discussing with @JamesGarethSmith  - it seems he's been following the rubocop default, which seems to point to this.

https://github.com/bbatsov/ruby-style-guide

There is also the rails style guide here : 

https://github.com/bbatsov/rails-style-guide

@JamesGarethSmith @slopboy  - you should both decide if these are the ones, and if there are any amendments / alterations necessary.

**Comment by JamesGarethSmith** [comment]
I'm happy to use that Ruby styleguide as is. The only thing I added to it is a line-length restriction of 120 chars.

I haven't activated the Rails style rules in Rubocop yet. I'll take a read through it and see what it's like. At first glance it seems very reasonable and it can be implemented just by passing a parameter to Rubocop. I just need to see how that can be integrated with the test runner.

Do you have anything to add here @slopboy ?

**Comment by Pushplaybang** [comment]
@JamesGarethSmith @slopboy awesome.    Code climate will run with whatever your rubocop setup is for static analysis, when doing commits, but locally I wouldn't know.  That's of course the next step is having accessible and easy to use processes for all of these.
