### ISSUE TITLE
PHP Coding Standards

### ISSUE THREAD

**Issue by Pushplaybang** [Nona-Creative/coding-standards#7]
# Scope

Php can be tricky, and while we seem to be using it less, I don't believe PHP will ever not be a part of our lives.  In order to write better PHP, I would like to propose that we as a company adopt the fig standards here: 

https://github.com/Nona-Creative/fig-standards/tree/master/accepted

including PSR-1, PSR-2, PSR-4 specifically. 

@Nona-Creative/nonabots  - fire at will.

**Comment by JamesGarethSmith** [comment]
@Pushplaybang Is it worth including a reference to http://www.phptherightway.com/ ?

**Comment by SkippyZA** [comment]
PSR is great, my only concern is that they enforce an 80 char line width. Working with namespaces and concise classes leads to longer file names which then result in horrible formatted code that is spread out across multiple lines.

I would suggest PSR with a 120 char line width.

@JamesGarethSmith great resource too.

**Comment by Pushplaybang** [comment]
@SkippyZA  - I'm happy with that, I'm also not a fan of tab stops 4 spaces wide which also make 80 char a bit short, but happy as long as we have a standard - I know that @JamesGarethSmith has the same amendment for Ruby, so let'ss go with it.

Can we get a second?  @ShaunEgan @royscheeren @darrynten @RollYourOwnEd ?

@JamesGarethSmith  - yeah thanks for the awesome link!

**Comment by ShaunEgan** [comment]
Yeah, I'm cool without that.

**Comment by ShaunEgan** [comment]
That should have been "with that". Not sure what happened.
